spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bookshop}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddlAuto: update